export const Queues = {
  PAYMENT_EXECUTE: 'payment-execute',
  PAYMENT_RETRY: 'payment-retry',
  SETTLEMENT_PROCESS: 'settlement-process',
  SETTLEMENT_RETRY: 'settlement-retry',
  JOURNAL_POSTING: 'journal-posting',
  NOTIFICATION_SEND: 'notification-send',
  RECONCILIATION_RUN: 'reconciliation-run',
  PAYROLL_PROCESS: 'payroll-process',
  ADVANCE_DISBURSE: 'advance-disburse',
  LOAN_PROCESS: 'loan-process',
  OUTBOX_RELAY: 'outbox-relay',
  DEAD_LETTER: 'dead-letter',
  AUDIT_LOG: 'audit-log',
} as const;

export const Jobs = {
  EXECUTE_PAYMENT: 'execute-payment',
  REVERSE_PAYMENT: 'reverse-payment',
  PAYMENT_INQUIRY: 'payment-inquiry',
  PROCESS_SETTLEMENT: 'process-settlement',
  RECONCILE_SETTLEMENT: 'reconcile-settlement',
  POST_JOURNAL: 'post-journal',
  CLOSE_PERIOD: 'close-period',
  GENERATE_TRIAL_BALANCE: 'generate-trial-balance',
  SEND_EMAIL: 'send-email',
  SEND_SMS: 'send-sms',
  SEND_PUSH: 'send-push',
  RUN_PAYROLL: 'run-payroll',
  GENERATE_PAYSLIP: 'generate-payslip',
  AUTO_MATCH: 'auto-match',
  PROCESS_EXCEPTION: 'process-exception',
  RELAY_EVENT: 'relay-event',
  RECORD_AUDIT: 'record-audit',
  PURGE_AUDIT: 'purge-audit',
} as const;
